name: Build site

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: mstksg/get-package@v1
    - name: Build static files
      run: |
        stack build
        stack exec site build
    - name: Push Changes
      run: |
        cp -a _site/. .
        git add -A
        git commit -m "Publish."
        git push origin develop

