name: Build site

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: mstksg/get-package@v1
    - name: Build
      run: |
        stack build
        git status

